Day: Wednesday

Sunday:
  Message: Feed the cat

Monday:
  Message: Water the plants

Tuesday:
  Message: Exercise regularly

Wednesday:
  Message: Take a bath

Thursday:
  Message: Feed the cat

Friday:
  Message: Water the plants

Saturday:
  Message: Exercise regularly
